backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor
media_folder: "images/uploads"
collections:
  - name: post
    label: Post
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "categories", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      